module.exports = [
	"Si fueras un producto, ¿cuál sería tu eslogan?",
	"Si dirigieras una película, ¿a qué género pertenecería?",
	"¿Qué le preguntarías a tu yo de dentro de veinte años?",
	"Si pudieras viajar en el tiempo, ¿viajarías al pasado o al futuro?",
	"Si fueses capaz de cambiar algo en el mundo... ¿qué cambiarías?",
	"Si te dijesen que eres inmortal y que ninguno de tus actos va a ser castigado, ¿qué sería lo primero que harías?",
	"Si pudieras cenar con cualquier personaje histórico, ¿a quién elegirías?",
	"¿Sin cuál de los cinco sentidos podrías vivir? (Vista, audición, olfato, gusto y tacto)",
	"Si comer y beber lo que quisieras no tuviese ninguna consecuencia, ¿qué comerías más a menudo?",
	"Si tuvieras diez segundos para un deseo, ¿qué pedirías?",
	"¿Qué superpoder querrías tener?¿Cómo comprobarías si fue antes el huevo o la gallina?",
	"¿Cómo comprobarías si fue antes el huevo o la gallina?",
	"¿En qué época te hubiese gustado vivir?",
	"¿Cuál ha sido el sueño más extraño que has tenido nunca?",
	"Imagina que te confundieran con un actor/actriz famoso. ¿Con quién sería?",
	"Si pudieras encerrar a alguien de por vida, ¿a quién sería?",
	"Si un oso te atacara, ¿qué harías para sobrevivir?",
	"¿Qué es lo más loco que has hecho por amor?",
	"¿Qué parte de tu cuerpo te gusta más y por qué?",
	"Si pudieses intercambiar tu vida con alguien, ¿con quién sería?",
	"¿Qué animal te gustaría ser y por qué?",
	"Si te tuvieras que poner un nombre a ti mismo, ¿cuál sería?",
	"¿Qué es lo más vergonzoso que te han pillado haciendo?",
	"¿Qué harías si te diera un ataque de risa en una situación inapropiada o en lugar del que no puedes salir?",
	"¿Qué canción odias pero sin embargo te sabes de memoria?",
	"Si fueras un fantasma que habita una casa encantada, ¿Cómo atraerías a la gente dentro?",
	"Si pudieses saber sólo una cosa del futuro, ¿qué preguntarías?",
	"Si te gastaran una broma pesada, ¿cómo te vengarías?",
	"¿Qué es lo más extraño que has hecho por comer algo que te apetecía?",
	"¿En qué ciudad en la que no has estado te gustaría gastar un millón de dólares?",
	"¿Quieres más a tu perro (o gato) que a algún otro miembro de tu familia?",
	"Si pudieras intercambiar dos personajes de dos películas, ¿qué cambio crees que haría las películas mas locas o inapropiadas?",
	"¿Qué animal sería más bonito si pasara a tener el tamaño de un gato?",
	"¿Cómo cambiaría tu país si todos, independientemente de su edad, pudieran votar?",
	"¿Qué película puedes ver una y otra vez sin cansarte?",
	"¿Qué dirías que está mal pero suena bien o correcto?",
	"Si pudieras ser inmune a un delito, ¿a cual te gustaría ser inmune?",
	"¿Qué crees que estará siempre de moda, sin importar cuánto tiempo pase?",
	"¿Qué obstáculos incluirías en la carrera de obstáculos mas loca y épica del mundo?",
	"¿Qué cosa te hace girar la cabeza cada vez que lo oyes?",
	" ¿Crees que deberían poder comprarse y venderse los riñones?",
	"¿Cómo sería un mundo poblado por clones tuyos?",
	"¿Crees que los alienígenas existen?",
	"¿Qué criatura mítica querrías que existiera?",
	"Si alguien narrara tu vida, ¿quién te gustaría que fuera el narrador?",
	"¿Cuál ha sido la película más inquietante que has visto?",
	"¿Qué celebridad, o grupo, crees que tienen los peores fans?",
	"¿Qué cosas te interesan que a la mayoría de la gente no le importen?",
	"¿Crees que los niños que nazcan hoy tendrán mejores o peores vidas que sus padres?",
	"¿Con qué personaje de programa de televisión crees que sería mas divertido intercambiarte una semana?",
    "Cuando seas viejo, ¿qué tipo de historias crees que los niños te pedirán que cuentes?",
    "¿Qué objeto inanimado sería el más molesto si reprodujera una música alegre y optimista mientras lo usas?",
    "¿Tienes alguna historia que empezara muy mal pero que, al final, acabase genial?",
    "¿Qué combinaciones de comidas raras disfrutas?",
    "¿Qué nombre le pondrías a un barco si tuvieras uno?",
    "¿Cuál es la forma más épica en que has visto a alguien dejar su trabajo o ser despedido?",
    "¿Qué estigma social crees que necesita superar la sociedad?",
    "¿Qué estigma social crees que necesita superar la sociedad?",
    "En el pasado, la gente era enterrada con los objetos que necesitarían en el más allá, ¿qué te gustaría enterrar contigo para poder usarlo en la otra vida?",
    "¿Alguna vez has sido amable con alguien solo para conseguir algo a cambio? ¿Con quien?",
    "¿De dónde sacas la mayoría de cosas con las que decoras tu casa?",
    "¿Qué comida te gustaría probar que no hayas comido nunca?",
    "¿Qué comida te parece deliciosa pero te da pereza comer?",
    "¿Quién ha sido tu profesor más loco o interesante?",
    "¿Qué cosas haces “de persona mayor”?",
    "¿Cuál es el vídeo a cámara lenta más sorprendente que has visto?",
    "¿Cuales son los lugares mas raros que has visitado?",
    "¿Qué persona famosa crees que es muy humilde?",
    "¿Qué sería lo peor que podrías escuchar estando bajo anestesia justo antes de una cirugía de corazón?",
    "¿Qué es lo más picante que has comido?",
    "¿Qué es lo más caro que has roto?",
    "¿En qué crees que eres mucho mejor de lo que realmente eres?",
    "¿Cuándo fue la última vez que le dijiste a alguien “te lo dije”?",
   	"¿Qué adivinanzas te sabes?",
    "¿Qué haces para quitarte el hipo?",
    "¿Qué invento crees que no se le da importancia, pero ha mejorado mucho el mundo?",
    "¿Qué cosas te molestan bastante pagar?",
    "¿Qué cosas te preocupan últimamente?",
    "¿Cuál es el edificio más interesante que has visto o en el que has estado?",
    "¿Cuáles son tus reglas más importantes cuando tienes una cita?",
    "¿Cómo sueles juzgar a las personas?",
    "¿Qué experimento, no ético, tendría el mayor impacto positivo en la sociedad?",
     "¿Cuándo fue la última vez que estuviste fisgoneando y encontraste algo que hubieras preferido no haberte encontrado?",
    "¿A que tema crees que la sociedad no le da la importancia que se merece?",
    " ¿Usas alguna cita de alguna película de vez en cuando? ¿Cual?",
    "¿Cuál es el chiste más divertido que te sabes de memoria?",
    "¿Cuándo fue la última vez que sentiste que tuviste una nueva oportunidad?",
    "¿Cuál es el nombre real más divertido que has escuchado?",
    "Si te mudaras a otro país pero solo pudieras llevarte un bolso de mano, ¿qué meterías?",
    "¿Que es lo mas irónico que has visto en tu vida?",
    "Si la magia fuera real, ¿qué hechizo intentarías aprender primero?",
    "¿Que objetivo crees que la humanidad no le está dedicando el suficiente esfuerzo para lograr?",
    "¿A qué juego has jugado más horas en tu vida?",
    "¿Cuál es la cama o silla más cómoda en la que has estado?",
   	"¿Cuál es la conversación más rara o loca que has escuchado?",
    "¿Qué artista o banda recomiendas siempre que alguien te pide una recomendación musical?",
    "Si pudieras hacer un viaje con todos los gastos pagados para ver un monumento famoso, ¿qué monumento elegirías?",
    "Si los animales pudieran hablar, ¿qué animal crees que sería el más pesado?",
    "¿Cuál es el juego más adictivo al que has jugado?",
    "¿Cual es la menor temperatura que has experimentado?"
]