module.exports = {
    0: "Juego Personalizado.",
    72: "Abismo de los Lamentos: Enfrentamiento en la nieve. 1v1",
    73: "Abismo de los Lamentos: Enfrentamiento en la nieve. 2v2",
    75: "Grieta del Invocador: Hexakill. 6v6",
    76: "Grieta del Invocador: URF",
    78: "Abismo de los Lamentos: Modo Espejo",
    83: "Grieta del Invocador: Cooperativo vs URF IA",
    98: "Bosque Retorcido: Hexakill. 6vs6",
    100: "Puente del Carnicero: Aram 5v5",
    310: "Grieta del Invocador: Nemesis",
    313: "Grieta del Invocador: Camorristas del Mercado Negro",
    317: "La Cicatriz de Cristal: Definitivamente no es Dominio",
    325: "Grieta del Invocador: Todo Aleatorio",
    400: "Grieta del Invocador: Reclutamiento. 5v5",
    420: "Grieta del Invocador: Clasificatoria Solo/Dúo. 5v5",
    430: "Grieta del Invocador: Selección Oculta. 5v5",
    440: "Grieta del Invocador: Clasificatoria Flexible. 5v5",
    450: "Abismo de los Lamentos: Aram. 5v5",
    600: "Grieta del Invocador: La caza de la Luna Sangrienta",
    610: "Estrella Oscura: Singularidad",
    700: "Grieta del Invocador: Clash",
    820: "Bosque Retorcido: Co-op vs IA. Principiante",
    830: "Grieta del Invocador: Co-op vs IA. Introducción",
    840: "Grieta del Invocador: Co-op vs IA. Principiante",
    850: "Grieta del Invocador: Co-op vs IA. Intermedio",
    900: "Grieta del Invocador: Urf",
    910: "La Cicatriz de Cristal: Leyenda del Rey Poro",
    920: "Abismo de los Lamentos: Leyenda del Rey Poro",
    940: "Grieta del Invocador: Asedio al Nexo",
    950: "Grieta del Invocador: Votación de Doom Bots",
    960: "Grieta del Invocador: Doom Bots",
    980: "Invasion: Normal",
    990: "Invasion: Embate",
    1000: "Sobrecarga: Proyecto Hunters",
    1010: "Grieta del Invocador: ARURF",
    1020: "Grieta del Invocador: One for All",
    1030: "Odisea: Extracción. Introducción",
    1040: "Odisea: Extracción. Cadete",
    1050: "Odisea: Extracción. Tripulante",
    1060: "Odisea: Extracción. Capitán",
    1070: "Odisea: Extracción. Embate",
    1090: "Teamfight Tactics",
    1100: "Teamfight Tactics: Clasificatoria",
    1111: "Teamfight Tactics: Pruebas",
    1300: "Nexus Blitz",
    1400: "Grieta del Invocador: Libro de Hechizos Definitivo",
    2000: "Grieta del Invocador: Tutorial 1",
    2010: "Grieta del Invocador: Tutorial 2",
    2020: "Grieta del Invocador: Tutorial 3"
}